Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(run.py:1): Gdk-CRITICAL **: 14:44:31.992: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
